### ISSUE TITLE
How to deploy it on windows 

### ISSUE THREAD

**Issue by Harshcs2002** [saket13/SAMS#1]
bro can you please tell how to deploy it on the windows ??

**Comment by saket13** [comment]
The procedure almost remains same for the Windows platform. If you face any issue/error please let me know here !!

**Comment by Harshcs2002** [comment]
you had told to run code  in root mode but i don't know to run in root mode for windows ?? help with that please

**Comment by saket13** [comment]
Try starting the terminal with "Run as administrator" mode in windows and then run the python file..Let me know if it still does not work.

**Comment by Harshcs2002** [comment]
lool bro what error i am getting

**Comment by saket13** [comment]
Start the terminal application using Run In Adminstrator mode and then run the python file.

**Comment by Harshcs2002** [comment]
again same issue :(

**Comment by saket13** [comment]
Please copy paste the exact error/screenshot !

**Comment by Harshcs2002** [comment]
Following images have been trained :
4.jpg
Traceback (most recent call last):
  File "E:\SAMS-master\attendance.py", line 79, in <module>
    image = face_recognition.load_image_file(IMAGE_DIRECTORY_PATH + str(filename))                 # Load Image
  File "E:\python\lib\site-packages\face_recognition\api.py", line 86, in load_image_file
    im = PIL.Image.open(file)
  File "E:\python\lib\site-packages\PIL\Image.py", line 2953, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'E:/SAMS-master/assets4.jpg'
[ WARN:0@7.143] global D:\a\opencv-python\opencv-python\opencv\modules\videoio\src\cap_msmf.cpp (539) `anonymous-namespace'::SourceReaderCB::~SourceReaderCB terminating async callback

**Comment by saket13** [comment]
There is no file in this path which you are trying to access.
'E:/SAMS-master/assets4.jpg'
